// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ImageData.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__IMAGEDATA_HPP
#define FAST_DDS_GENERATED__IMAGEDATA_HPP

#include <cstdint>
#include <utility>
#include <vector>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(IMAGEDATA_SOURCE)
#define IMAGEDATA_DllAPI __declspec( dllexport )
#else
#define IMAGEDATA_DllAPI __declspec( dllimport )
#endif // IMAGEDATA_SOURCE
#else
#define IMAGEDATA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define IMAGEDATA_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure ImageData defined by the user in the IDL file.
 * @ingroup ImageData
 */
class ImageData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ImageData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ImageData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData(
            const ImageData& x)
    {
                    m_width = x.m_width;

                    m_height = x.m_height;

                    m_data = x.m_data;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData(
            ImageData&& x) noexcept
    {
        m_width = x.m_width;
        m_height = x.m_height;
        m_data = std::move(x.m_data);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData& operator =(
            const ImageData& x)
    {

                    m_width = x.m_width;

                    m_height = x.m_height;

                    m_data = x.m_data;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData& operator =(
            ImageData&& x) noexcept
    {

        m_width = x.m_width;
        m_height = x.m_height;
        m_data = std::move(x.m_data);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ImageData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ImageData& x) const
    {
        return (m_width == x.m_width &&
           m_height == x.m_height &&
           m_data == x.m_data);
    }

    /*!
     * @brief Comparison operator.
     * @param x ImageData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ImageData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            uint32_t _width)
    {
        m_width = _width;
    }

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport uint32_t width() const
    {
        return m_width;
    }

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport uint32_t& width()
    {
        return m_width;
    }


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            uint32_t _height)
    {
        m_height = _height;
    }

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport uint32_t height() const
    {
        return m_height;
    }

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport uint32_t& height()
    {
        return m_height;
    }


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::vector<uint8_t>& _data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::vector<uint8_t>&& _data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::vector<uint8_t>& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::vector<uint8_t>& data()
    {
        return m_data;
    }



private:

    uint32_t m_width{0};
    uint32_t m_height{0};
    std::vector<uint8_t> m_data;

};

#endif // _FAST_DDS_GENERATED_IMAGEDATA_HPP_


